services:

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  payment-core:
    build: ./payment-core

  fraud:
    build: ./fraud
    ports:
      - "8001:8001"
